import {specificColor} from "../Colors";

export const styles = {
    container: {
      width: "100%",
      height: "100%",
      padding: "0px 30px 0px 30px",
    },
    contentContainer1: {
      width: "100%",
      height: 60,
      paddingTop: 15,
      paddingRight: 20,
      paddingBottom: 15,
      paddingLeft: 20,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    contentContainer2: {
      width: "100%",
      height: 91,
      padding: 20,
      gap: 10,
    },
    counterContainer: {
      width: "90%",
      height: 24,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    answersContainer: {
      width: "100%",
      height: 265,
      paddingTop: 10,
      paddingRight: 20,
      paddingBottom: 10,
      paddingLeft: 20,
      gap: 15,
      alignItems: "center",
    },
    contentContainer3: {
      width: "100%",
      height: 302,
      paddingTop: 70,
      paddingRight: 10,
      paddingBottom: 70,
      paddingLeft: 10,
      gap: 10,
      alignItems: "center",
    },
    buttonsContainer: {
      height: 40,
      paddingTop: 175,
      gap: 15,
    },
    textStyle: {
      fontFamily: "Roboto",
      fontSize: 20,
      fontWeight: "500",
      lineHeight: 30,
      fontWeight: "bold",
      textAlign: "center",
      textUnderlinePosition: "from-font",
      textDecorationSkipInk: "none",
    },
    counterTextStyle: {
      fontFamily: "Roboto",
      fontSize: 16,
      fontWeight: "500",
      lineHeight: 24,
      color: specificColor,
      textAlign: "center",
      textUnderlinePosition: "from-font",
      textDecorationSkipInk: "none",
    },
    overlay: {
      position: "absolute",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    thankYouContainer: {
      width: "100%",
      height: 400,
      paddingTop: 40,
      paddingRight: 10,
      paddingBottom: 70,
      paddingLeft: 10,
      marginVertical: 10,
      gap: 10,
      alignItems: "center",
    },
    thankYouText: {
      fontFamily: "Roboto",
      fontSize: 20,
      fontWeight: "bold",
      textUnderlinePosition: "from-font",
      textDecorationSkipInk: "none",
    },
};