export const styles = {
    defaultBox: {
      bg: "white",
      borderRadius: "10px",
      width: "190px",
      height: "70px",
      maxWidth: "100%",
      padding: "6px",
      boxShadow: "0px 2px 10px 0px #00000040",
      shadow: 8,
      elevation: 5,
    },
    variantTwoAndThreeBox: {
        bg: "white",
        borderRadius: "10px",
        width: "100%",
        height: "90px",
        maxWidth: "100%",
        padding: "6px",
        boxShadow: "0px 2px 10px 0px #00000040",
        shadow: 8,
        elevation: 5,
    },
    headerBox:{
      width: "100%",
      height: "18px",
    },
    middleBox: {
      display: "flex",
      justifyContent: "flex-end",
      width: "100%",
      height: "23px",
      gap: "10px",
    },
    bottomBoxDefault: {
      width: "100%",
      height: "18px",
    },
    bottomBoxVariantTwoAndThree: {
      width: "100%",
      height: "43px",
      display:"flex",
      alignItems: "flex-end",
      justifyContent: "center",
    },
    bonusNameText: {
      fontFamily: "Roboto",
      fontSize: "12px",
      lineHeight: "18px",
      fontWeight: "500",
      textAlign: "left",
    },
    orgNameText: {
      fontFamily: "Roboto",
      fontSize: "10px",
      lineHeight: "15px",
      fontWeight: "500",
      textAlign: "left",
      color: "#767676", 
    },
  };
  