

export const styles = {
 shadow:{
    position:'absolute',
    top:0,
    left:0,
    width:'120%',
    height:'100%',
    zIndex:1,
    backgroundColor:"rgba(118, 118, 118, 0.5)",
  
 },
  container: {
    width: 362,
    height: 214,
    backgroundColor: "white",
    borderRadius: 10,
    zIndex:9999,
  },
  topContainer: {
    width: "100%",
    height: 55,
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(118, 118, 118, 0.5)",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  middleContainer: {
    width: "100%",
    height: 104,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(118, 118, 118, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  bottomContainer: {
    width: "100%",
    height: 55,
    paddingVertical: 10,
    paddingHorizontal: 90,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  leftContainer: {
    width: 85,
    height: 24,
    justifyContent: "center",
  },
  rightContainer: {
    width: 22,
    height: 22,
    justifyContent: "center",
  },
  titleText: {
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 24,
    textAlign: "center",
    color: "#000000",
  },
  messageContainer: {
    width: 275,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
  },
  messageText: {
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 24,
    textAlign: "center",
    color: "#000000",
  },
  button: {
    width: 70,
    height: 37,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
    borderRadius: 4,
  },
  buttonText: {
    fontFamily: "Roboto",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 21,
    color: "#000000",
  },
};
