export const styles = {
  container: {
    width: 402,
    paddingVertical: 10,
    paddingHorizontal: 20,
    gap: 20,
    flexDirection: "row",
    alignItems: "center",
    // borderWidth: 1,
  },
  avatarContainer: {
    width: 72,
    height: 72,
    paddingVertical: 10,
    borderRadius: 36,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#767676",
  },
  textContainer: {
    width: 210,
    height: 72,
    paddingVertical: 10,
    justifyContent: "center",
    borderColor: "#767676",
  },
  textContainerVariant2: {
    width: 185,
    height: 72,
    paddingVertical: 10,
    justifyContent: "center",
    borderColor: "#767676",
  },
  subContainer: {
    width: 185,
    height: 27,
    justifyContent: "center",
  },
  userNameText: {
    fontFamily: "Roboto",
    fontSize: 18,
    fontWeight: "500",
    lineHeight: 27,
    textAlign: "left",
    color: "#000000",
  },
  userOccupationText: {
    fontFamily: "Roboto",
    fontSize: 18,
    fontWeight: "500",
    lineHeight: 27,
    textAlign: "left",
    color: "#767676",
  },
  iconContainer: {
    width: 38,
    height: 46,
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#767676",
  },
  button: {
    width: 79,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 10,
    backgroundColor: "#f0f0f0",
    borderRadius: 4,
  },
};
