import { background } from "../Colors";

export const styles = {
  container: {
    width: "100%",
    height: "100%",
    padding: "0px 30px 0px 30px",
  },
  tabsContainer: {
    width: "100%",
    height: "44px",
    padding: "0px 30px 0px 30px",
  },
  contentContainer: {
    width: "100%",
    flex: 1,
    gap: "10px",
  },
  contentContainer1: {
    width: "100%",
    height: 60,
    paddingTop: 15,
    paddingRight: 20,
    paddingBottom: 15,
    paddingLeft: 20,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  contentContainer2: {
    width: "100%",
    height: 400,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(118, 118, 118, 0.5)",
    alignItems: "center",
  },
  questionNamePlusDeleteIconContainer: {
    width: "100%",
    height: 42,
    paddingTop: 2,
    paddingRight: 20,
    paddingBottom: 2,
    paddingLeft: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  answersContainer: {
    width: "100%",
    height: 265,
    paddingTop: 10,
    paddingRight: 20,
    paddingBottom: 10,
    paddingLeft: 20,
    gap: 15,
  },
  questionAnswerContainer: {
    width: "100%",
    paddingTop: 10,
    paddingRight: 20,
    paddingBottom: 10,
    paddingLeft: 20,
  },
  contentContainer3: {
    // marginBottom: "20%",
    width: "100%",
    height: 246,
    padding: 10,
    justifyContent: "space-between",
    alignItems: "center",
  },
  inputFieldContainer: {
    width: "100%",
    height: 55,
    gap: 10,
  },
  textStyle: {
    fontFamily: "Roboto",
    fontSize: 20,
    fontWeight: "500",
    lineHeight: 30,
    fontWeight: "bold",
    textAlign: "center",
    textUnderlinePosition: "from-font",
    textDecorationSkipInk: "none",
  },
  inputField: {
    height: 43,
    gap: 10,
  },
};